#services:
#    app_privilege.example:
#        class: App\PrivilegeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
  app_privilege.security:
    class: App\PrivilegeBundle\Controller\SecurityController
    autowire: true
    tags: ['controller.service_arguments']
